### ISSUE TITLE
 ERROR webdriver: RequestError: read ECONNRESET

### ISSUE THREAD

**Issue by Nguonchhay** [TuHuynhVan/mobile-automation-test-android#1]
When I run the command `npm test run ./test-configs/android.js`, I got below error:
`
[0-0] 2020-12-02T09:05:35.611Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4732
    at ClientRequest.<anonymous> (/Users/nguonchhay/nguonchhay/automation-test/mobile-automation-test-android/node_modules/got/dist/source/core/index.js:940:25)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at ClientRequest.origin.emit (/Users/nguonchhay/nguonchhay/automation-test/mobile-automation-test-android/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
2020-12-02T09:05:35.612Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "http://localhost:4732/wd/hub", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
    at startWebDriverSession (/Users/nguonchhay/nguonchhay/automation-test/mobile-automation-test-android/node_modules/webdriver/build/utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0]  Error:  Failed to create session.
Unable to connect to "http://localhost:4732/wd/hub", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-0] FAILED in com.nguonchhay.sampleapp - /src/test_scripts/account/TC_001_Login.js
2020-12-02T09:05:35.726Z INFO @wdio/cli:launcher: Run onComplete hook
Report successfully generated to allure-report
Allure report successfully generated

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:05

2020-12-02T09:05:39.417Z INFO @wdio/local-runner: Shutting down spawned worker
2020-12-02T09:05:39.672Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-12-02T09:05:39.673Z INFO @wdio/local-runner: shutting down
npm ERR! Test failed.  See above for more details.
`

I tried to find the solution on the Internet but there is no solution. Could you help to guide how to make it work?

Thanks

**Comment by TuHuynhVan** [comment]
@Nguonchhay Please make sure to started appium server on target port.
`RequestError: connect ECONNREFUSED 127.0.0.1:4732`
